//
// Created by Christopher Yarp on 10/17/19.
//

#ifndef CYCLOPSASCIILINK_FEEDBACKDEFINES_H
#define CYCLOPSASCIILINK_FEEDBACKDEFINES_H

#define FEEDBACK_DATATYPE uint32_t

#endif //CYCLOPSASCIILINK_FEEDBACKDEFINES_H
