name: CMake CI

#Only Tests Build

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CXX: clang++
  CC: clang

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    #Try with both GCC and clang
    #See https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    strategy:
      fail-fast: false #See https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      matrix:
        compiler: [clang, gcc] 

    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/cyclopsASCIILink

    
    - name: Install Dependencies
      shell: bash
      run: if [[ ${{ matrix.compiler }} == "clang" ]]; then sudo apt install clang; elif [[ ${{ matrix.compiler }} == "gcc" ]]; then sudo apt install gcc g++; fi; sudo apt install cmake libboost-all-dev libxerces-c-dev graphviz doxygen

    - name: Set Compiler
      shell: bash
      # Using method in https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      # to conditionally set the output variable based on the matrix compiler value
      run: if [[ ${{ matrix.compiler }} == "clang" ]]; then echo "CC=clang" >> $GITHUB_ENV; echo "CXX=clang++" >> $GITHUB_ENV; elif [[ ${{ matrix.compiler }} == "gcc" ]]; then echo "CC=gcc" >> $GITHUB_ENV; echo "CXX=g++" >> $GITHUB_ENV; fi 

    - name: Report Compiler Versions
      shell: bash
      run: echo ${CXX}; echo ${CC}; ${CXX} --version; ${CC} --version
      
    - name: Clone Test Files
      uses: actions/checkout@v2
      with:
        repository: ucb-cyarp/cyclopsASCIILink-testfiles
        token: ${{ secrets.READONLY_PAT }}
        ref: 9565a142518942885367f41fc3c2a455ba81e484
        path: ${{github.workspace}}/cyclopsASCIILink-testfiles
        
    - name: Copy Test Files
      run: cp ${{github.workspace}}/cyclopsASCIILink-testfiles/vitisIncludes/* ${{github.workspace}}/cyclopsASCIILink/src/vitisIncludes/.

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/cyclopsASCIILink/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/cyclopsASCIILink

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/cyclopsASCIILink

      
